server:
  port: 13304
spring:
  application:
    name: lemon-backend-blog
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/native?useUnicode=true&characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 520.hate
  # mvc
  mvc:
    static-path-pattern: /**
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: static/**
  #日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
