server:
  port: 13304
spring:
  application:
    name: lemon-backend-blog
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/native?useUnicode=true&characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 520.hate